FROM quay.io/toolbx/arch-toolbox:latest

WORKDIR /tmp

# Install:
# - yay, because it is nice to have
# - a bunch of random utils: fzf, ripgrep, fd, jq, openbsd-netcat
# - neovim, because I always need it
# - npm, because a bunch of useful LSPs depend on it (json, yaml)

RUN pacman -Syu --noconfirm \
    && pacman -S --needed --noconfirm git base-devel \
    && useradd -m -G wheel builder -u 2000\
    && passwd -d builder \
    && echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && runuser -u builder -- git clone https://aur.archlinux.org/yay-bin.git \
    && cd yay-bin \
    && runuser -u builder -- makepkg \
    && pacman -U --noconfirm ./yay-bin-*.pkg.tar.zst \
    && cd .. \
    && rm -rf yay-bin \
    && pacman -S --noconfirm neovim fzf ripgrep fd jq openbsd-netcat npm python unzip

LABEL com.github.containers.toolbox="true" \
      name="lfdwm-base"
